framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    php_errors:
        log: true

    http_client:
        default_options:
            retry_failed: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
