framework:
    messenger:
        failure_transport: failed

        transports:
            failed: 'doctrine://default?queue_name=failed'
            solve: 'doctrine://default?queue_name=solve'

        routing:
            'App\Dto\SolveMessage': solve
